# Generated by Django 4.2.1 on 2023-05-28 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CentralEmployee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='centralemployee', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('views_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tourist', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='storage/videos/')),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalEmployee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regionalemployee', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.region')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest_Transportation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.pointofinterest')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.transportation')),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.theme'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='storage/photos/point_of_interest')),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('opendate', models.DateField()),
                ('closedate', models.DateField()),
                ('image', models.ImageField(upload_to='storage/photos/photoevent')),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.pointofinterest')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiyahaDzApp.tourist')),
            ],
        ),
    ]
