from django.urls import path
from .views import *
from .models import *


urlpatterns = [
    path('points-of-interest/', PointOfInterestListAPIView.as_view(),
         name='point-of-interest-list'),
    path('points-of-interest/<int:pk>/',
         PointOfInterestDetailAPIView.as_view(), name='point-of-interest-detail'),
    path('opening-hours/', OpeningHoursListAPIView.as_view(),
         name='opening-hours-list'),
    path('opening-hours/<int:pk>/', OpeningHoursDetailAPIView.as_view(),
         name='opening-hours-detail'),
    path('categories/', CategoryListAPIView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailAPIView.as_view(),
         name='category-detail'),
    path('themes/', ThemeListAPIView.as_view(), name='theme-list'),
    path('themes/<int:pk>/', ThemeDetailAPIView.as_view(), name='theme-detail'),
    path('comments/', CommentListAPIView.as_view(), name='comment-list'),
    path('comments/<int:pk>/', CommentDetailAPIView.as_view(), name='comment-detail'),
    path('events/', EventListAPIView.as_view(), name='event-list'),
    path('events/<int:pk>/', EventDetailAPIView.as_view(), name='event-detail'),
    path('regions/', RegionListAPIView.as_view(), name='region-list'),
    path('regions/<int:pk>/', RegionDetailAPIView.as_view(), name='region-detail'),
    path('cities/', CityListAPIView.as_view(), name='city-list'),
    path('cities/<int:pk>/', CityDetailAPIView.as_view(), name='city-detail'),
    path('transportations/', TransportationListAPIView.as_view(),
         name='transportation-list'),
    path('transportations/<int:pk>/',
         TransportationDetailAPIView.as_view(), name='transportation-detail'),
    path('point-of-interest-transportations/', PointOfInterestTransportationListAPIView.as_view(),
         name='point-of-interest-transportation-list'),
    path('point-of-interest-transportations/<int:pk>/',
         PointOfInterestTransportationDetailAPIView.as_view(), name='point-of-interest-transportation-detail'),
    path('photos/', PhotoListAPIView.as_view(), name='photo-list'),
    path('photos/<int:pk>/', PhotoDetailAPIView.as_view(), name='photo-detail'),
    path('videos/', VideoListAPIView.as_view(), name='video-list'),
    path('videos/<int:pk>/', VideoDetailAPIView.as_view(), name='video-detail'),
    path('regional-employees/', RegionalEmployeeListAPIView.as_view(),
         name='regional-employee-list'),
    path('regional-employees/<int:pk>/',
         RegionalEmployeeDetailAPIView.as_view(), name='regional-employee-detail'),
    path('central-employees/', CentralEmployeeListAPIView.as_view(),
         name='central-employee-list'),
    path('central-employees/<int:pk>/',
         CentralEmployeeDetailAPIView.as_view(), name='central-employee-detail'),
    path('tourists/', TouristListAPIView.as_view(), name='tourist-list'),
    path('tourists/<int:pk>/', TouristDetailAPIView.as_view(), name='tourist-detail'),
]
